config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :ingredients
  resources :recipes

  get '/search', to: 'recipes#search', as: 'search'
end

app/models/allergy.rb
class Allergy < ApplicationRecord
    belongs_to :user
    belongs_to :ingredient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :allergies
    has_many :users, through: :allergies
    has_many :ingredient_recipes
    has_many :recipes, through: :ingredient_recipes
end

app/models/ingredient_recipe.rb
class IngredientRecipe < ApplicationRecord
    belongs_to :ingredient
    belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user

    has_many :ingredient_recipes
    has_many :ingredients, through: :ingredient_recipes

    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :recipes
    has_many :allergies
    has_many :ingredients, through: :allergies

    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all

  end

  def search
    puts "test"
    @ing_count = Recipe.all.map do |recipe|
      recipe.ingredients.count
      end

    render :index
  end


  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  # def create
  #   @recipe = Recipe.create(recipe_params)
  #    redirect_to recipe_path(@recipe)
  # end

  def create
    @recipe = Recipe.create(recipe_params)
    if @recipe.valid?
        @recipe.save
        redirect_to recipe_path(@recipe)
    else
    flash[:message] ="yo recipe ain't right"
    redirect_to new_recipe_path
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    # @recipe.update(params.require(:recipe).permit(:name, :user_id))
    @recipe.update(recipe_params)

    if @recipe.valid?
      redirect_to @recipe
    else
      flash[:message] ="yo recipe ain't right"
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  private

    def recipe_params
      params.require(:recipe).permit(:name, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAllgergenLab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
    <% end -%>
    <%= yield %>
  </body>
</html>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%# if flash[:message] %>
<%#=flash[:message]%>
<%# end %>


<%= form_for @recipe do |f| %>
  Name: <%= f.text_field :name %><br />
  What User?:<%=f.collection_select( :user_id, User.all, :id, :name)%>
  What Ingredient?:<%=f.collection_select( :ingredient_ids, Ingredient.all, :id, :content)%>
  <%= f.submit "Edit the new recipe" %>
<% end %>

<%= link_to 'Back', recipes_path %>  

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>

    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.user_id %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>


      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>


<%= form_with(url: "/search", method: "get") do %>
  <%= label_tag(@ing_count, "Number of ingredients:") %>
  <%= text_field_tag(@ing_count) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= form_for @recipe do |f| %>
  Name: <%= f.text_field :name %><br />
  What User?:<%=f.collection_select( :user_id, User.all, :id, :name)%>
  What Ingredient?:<%=f.collection_select( :ingredient_ids, Ingredient.all, :id, :content)%>
  <%= f.submit "Create a new recipe" %>
<% end %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>User:</strong>
  id: <%= @recipe.user_id %><br>
  name: <%= @recipe.user.name%><br>
  age: <%= @recipe.user.age%><br>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>